name: 'Apply terraform'
description: 'Apply terraform'
inputs:
  dir:  
    description: 'Directory of module'
    required: true
  key:  
    description: 'Key name of state'
    required: true
outputs:
  output:
    description: 'Output string'
    value: ${{ steps.set-output.outputs.string }}
runs:
  using: "composite"
  steps:
    - name: Terraform Init
      shell: bash
      run: cd ${{inputs.dir}} && terraform init -reconfigure -backend-config="region=${AWS_REGION}" -backend-config="bucket=${TF_STATE_S3_BUCKET}" -backend-config="key=${{inputs.key}}.tfstate"

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      shell: bash
      run: cd ${{inputs.dir}} && terraform fmt -check 

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      shell: bash
      run: cd ${{inputs.dir}} && terraform plan -out tfplan

    - name: Terraform Apply
      shell: bash
      run: cd ${{inputs.dir}} && terraform apply -auto-approve tfplan
