repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: pretty-format-json
        args:
          - --autofix
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.353
    hooks:
      - id: checkov
        args:
          - --config-file
          - .checkov.yaml
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
        - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yaml
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

  # # Uncomment the following lines for enabling Python hooks
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: pytest
  #       args:
  #         - ./tests/unit_tests
  #       language: system
  #       types: [python]
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.8.2
  #   hooks:
  #     - id: bandit
  #       args:
  #         - -x
  #         - tests
