name: Terraform Deploy

permissions:
  id-token: write ## This is required for requesting the JWT
  contents: read ## This is required for actions/checkout
  pull-requests: write ## This is required to add comments to Pull Requests
  deployments: write ## This is required to deactivate deployments

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.tf*"
      - ".github/workflows/deploy.yml"
  push:
    branches:
      - "main"
    paths:
      - "**.tf*"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    name: Progressive Deployment
    uses: ./terraform-reusable.yml
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        include:
          - environment: dev
            region: us-east-1
          - environment: test
            region: ap-southeast-2
          - environment: prod
            region: ap-southeast-2
    with:
      deploy: true
      tf-version: ${{ vars.TF_VERSION }}
      tf-organization: ${{ vars.TF_ORGANIZATION }}
      tf-hostname: ${{ vars.TF_HOSTNAME }}
      tf-workspace: ${{ vars.APP_NAME }}-${{ matrix.environment }}
      aws-region: ${{ matrix.region }}
      environment: ${{ matrix.environment }}
      ref: v1.2.0
    secrets:
      tf-token: ${{ secrets.TF_TOKEN }}
