version: '3.8'

services:

  ## devcontainer:
  k8s:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      # - ..:/workspaces:cached
      - ../..:/workspaces:cached
      - $HOME/.ssh/:/home/vscode/.ssh/

    ## Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # command: /bin/sh -c "while sleep 1000; do :; done" 

    ## Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  redis:
    image: redis:${REDIS_VERSION:-6.0.9}

  db:
    image: postgres:16-alpine
    command: ["-c", "fsync=off", "-c", "full_page_writes=off", "-c", "synchronous_commit=off"]
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  postgres-data:
