apiVersion: v1
kind: Service
metadata:
  name: eks-windows-service
  namespace: eks--app
  labels:
    app: eks-windows-app
spec:
  selector:
    app: eks-windows-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
